// Auto-generated by deployment script - DO NOT EDIT MANUALLY
import { ContractAddresses } from '../types';

export const contractAddresses: ContractAddresses = {
  "verificationRegistry": "0x6e7CDc10723e154Db844e5c892De8b9e5CBA7E72",
  "resumeNFT": "0xec3dFc191BD0C26f91AF74E8FA584D2D40AB2451",
  "networkName": "sepolia",
  "deploymentTimestamp": "2025-05-06T01:14:01.995Z"
};

export default contractAddresses;
