// Auto-generated by deployment script - DO NOT EDIT MANUALLY
import { ContractAddresses } from '../types';

export const contractAddresses: ContractAddresses = {
  "verificationManager": "0x5f26f8FaF2842FF674B0185151BcbdecAA8DDFE2",
  "resumeNFT": "0xbBb3940C4A47D829D800eCAfC671F5744a467c09",
  "networkName": "sepolia",
  "deploymentTimestamp": "2025-05-15T10:55:38.666Z"
};

export default contractAddresses;
