// Auto-generated by deployment script - DO NOT EDIT MANUALLY
import { ContractAddresses } from '../types';

export const contractAddresses: ContractAddresses = {
  "verificationRegistry": "0x9ec506BEd2BFC0076670521418fD73e26911A2d7",
  "resumeNFT": "0x6fA53398bBaa1977a723a944Ff8aC3C50AE935aD",
  "networkName": "sepolia",
  "deploymentTimestamp": "2025-05-09T10:38:28.015Z"
};

export default contractAddresses;
